# NumPy Essentials Practice Exercises Overview:
Time to test the knowledge on NumPy. Lets start with simple task and move on to more challenging ones!<br>
**Good Luck**<br>

&#9758; *Please note, there are several ways to get the required output, so your code could be different then what is provided in this notebook. <br>As long as you are getting the tasks done, it is fine at this stage. *

**1. What is the major difference between "`Vector`" and "`Matrix`"?**

In [1]:
#A vector is a one-dimensional array of numbers, representing quantities such as direction or magnitude. A matrix is a two-dimensional array arranged in rows and columns, used for organizing data or performing operations like multiplication. Vectors represent lists of values, while matrices represent tables of values.

**2. How to import `NumPy` library?** 

In [2]:
# import numpy as np


**3. Convert the given Python list into NumPy array and check its data type**

In [4]:
list_1 = [1,2,3,4,5]

In [1]:
# Given Python list
list_1 = [1, 2, 3, 4, 5]

# Convert list to NumPy array
array_1 = np.array(list_1)

# Check data type of NumPy array
data_type = array_1.dtype

print("NumPy array:", array_1)
print("Data type of NumPy array:", data_type)

NameError: name 'ytyutu' is not defined

(array([1, 2, 3, 4, 5]), numpy.ndarray)

**4. Generate `array [0,1,2,3,4,5]` using NumPy built-in function, `arange()`**

In [7]:
array_1 = np.arange(6)

print("Generated array:", array_1)


array([0, 1, 2, 3, 4, 5])

**5. Generate an `array of "5" zeros` **

In [9]:
array_zeros = np.zeros(5)

print("Array of 5 zeros:", array_zeros)

array([ 0.,  0.,  0.,  0.,  0.])

**6. Generate the following `matrix`.**

In [11]:
matrix = np.zeros((3, 4))

print("Generated matrix:")
print(matrix)

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

**7. Generate** `[1.,1.,1.,1.,1.]` **using NumPy built-in function?**

In [13]:
# Generate array of 5 ones
array_ones = np.ones(5)

print("Array of 5 ones:", array_ones)

[ 1.  1.  1.  1.  1.]


**8. Generate an array of "5" tens.**

In [15]:
array_tens = np.full(5, 10)

print("Array of 5 tens:", array_tens)

array([10., 10., 10., 10., 10.])

**9. Use `arange()` to generate an array of even numbers between 50 and 100.**<br>
*50 and 100 are not included*

In [17]:
array_even = np.arange(52, 100, 2)

print("Array of even numbers between 50 and 100 (exclusive):")
print(array_even)

array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90, 92, 94, 96, 98])

**10. Generate an array of 10 linearly spaced points between 0 and 1.**<br>
**Output step size as well?**

In [19]:
array_linspace = np.linspace(0, 1, 10)

# Calculate the step size
step_size = array_linspace[1] - array_linspace[0]

print("Array of 10 linearly spaced points between 0 and 1:")
print(array_linspace)
print("Step size:", step_size)

(array([ 0.        ,  0.11111111,  0.22222222,  0.33333333,  0.44444444,
         0.55555556,  0.66666667,  0.77777778,  0.88888889,  1.        ]),
 0.1111111111111111)

**11. Perform the following tasks:**
* Generate a **`vector array of 25`** numbers using **`arange()`**
* write a code to convert the vector array into **`2-D matrix using reshape`**
* can we use **`shape`** instead of reshape as well?

In [21]:
# To avoid overwritinavector_array = np.arange(25)

# Convert the vector array into a 2-D matrix using reshape
matrix_2d_reshape = vector_array.reshape((5, 5))

# Alternatively, you can use shape to achieve the same result
matrix_2d_shape = vector_array.reshape(5, 5)

print("Original vector array:")
print(vector_array)
print("\nMatrix using reshape:")
print(matrix_2d_reshape)
print("\nMatrix using shape:")
print(matrix_2d_shape)g the output, please code here 

In [22]:
# Generating vector array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
# To avoid overwriting the output, please code here 

In [24]:
# reshape to convert into 2-d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
# To avoid overwriting the output, please code here 

In [26]:
# Using shape

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**12. Please generate the following matrix.**

In [27]:
# To avoid overwriting the output, please code here 

In [14]:
array_linear = np.arange(0.1, 2.6, 0.1)

# Reshape the linear array into a 2-D matrix of shape (5, 5)
matrix = array_linear.reshape((5, 5))

print("Generated matrix:")
print(matrix)

array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ],
       [1.1, 1.2, 1.3, 1.4, 1.5],
       [1.6, 1.7, 1.8, 1.9, 2. ],
       [2.1, 2.2, 2.3, 2.4, 2.5]])

**13. Write a code to generate the output below, use "`linspace()`" and "`print()`"**

In [29]:
# To avoid overwriting the output, please code here 

In [27]:
# Generate a linearly spaced array of numbers from 0 to 24 with 25 elements
array_linear = np.linspace(0, 24, 25, dtype=int)

# Reshape the linear array into a 2-D matrix of shape (5, 5)
matrix = array_linear.reshape((5, 5))

# Print the matrix
print(matrix)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**14. What is the main difference between `linspace()` and `arange()`?**

In [31]:
#`linspace()` generates evenly spaced numbers over a specified interval by dividing it into the specified number of points. `arange()` generates numbers within a range with a specified step size, excluding the stop value. `linspace()` is useful for a fixed number of points, while `arange()` provides control over step size.

**15. How to generate a single random integer number using NumPy built-in function?**

In [32]:
# To avoid overwriting the output, please code here 

In [ ]:
# Generate a single random integer between 0 and 9
random_integer = np.random.randint(10)

print("Random integer:", random_integer)

**16. Write a code to generate a 7x5 matrix of 35 random numbers? use rand here** <br>
*Notice, there are no ( ) in the output matrix!*

In [34]:
# To avoid overwriting the output, please code here 

In [35]:
# Generate a 7x5 matrix of random numbers
matrix_random = np.random.rand(7, 5)

print("Generated matrix of random numbers:")
print(matrix_random)

[[ 0.99598801  0.07546767  0.17484793  0.25229956  0.4693597 ]
 [ 0.5591561   0.5007227   0.93630239  0.48747691  0.78658124]
 [ 0.98923838  0.04124599  0.71326198  0.51252888  0.36130539]
 [ 0.11558779  0.52914213  0.31134907  0.8047612   0.25759207]
 [ 0.87331331  0.77104413  0.960445    0.1732589   0.83339285]
 [ 0.99839604  0.78268012  0.66487603  0.14509928  0.05670129]
 [ 0.15932364  0.848172    0.51343887  0.06309231  0.29250649]]


**17. Generate the following matrix using NumPy's built-in method for identity matrix.**

In [36]:
# To avoid overwriting the output, please code here 

In [30]:
# Generate a 5x5 identity matrix with diagonal value 5
matrix_identity = 5 * np.eye(5)

print("Generated identity matrix:")
print(matrix_identity)

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

### You must be feeling comfortable using NumPy now!
# Great Job and Good Luck 